
const String baseUrl = "BASE_URL";
const String imageBaseUrl = "IMAGE_BASE_URL";
const String sandwichBaseUrl = "SADNWICH_BASE_URL";
const String registerUrl = "$baseUrl/auth/sign-up";
const String loginUrl = "$baseUrl/auth/login";
const String getCategoriesUrl = "$baseUrl/categories";
const String getAdsUrl = "$baseUrl/advertisement/list";
const String getZonesUrl = "$baseUrl/zone/list";
const String getAllRestaurantsUrl = "$baseUrl/restaurants/get-restaurants/all";
const String getRestaurantDetailsUrl = "$baseUrl/restaurants";
const String getSandwichDetailsUrl = "$baseUrl/products/details";
const String getPopularProductsUrl = "$baseUrl/products/popular?limit=10&offset=1";
const String getWalletDetailsUrl = "$baseUrl/customer/wallet/summary";
const String updateUserInfoUrl = "$baseUrl/register/update-info";
const String uploadProfileImageUrl = "$baseUrl/register/update-info";
const String getSearchResultUrl = "$baseUrl/products/food-or-restaurant-search";
const String getAllOrdersUrl = "$baseUrl/customer/order/list";
const String placeOrderUrl = "$baseUrl/customer/order/place-multi";
